Parameters:
  s3bucketname:
    Type: String
    Default: ato-dis-infra-build-pipeline-outputs-devtest
  vsslnzip:
    Type: String
    Default: vssln.zip
  kmsalias:
    Type: String
    Default: alias/KMS-DIS-DockerImageBuilder
  lambdarole:
    Type: String
    Default: arn:aws:iam::830486629506:role/ato-role-dis-testiac-lambda
  admincbrole:
    Type: String
  jinja:
    Type: String
    Default: jinja.zip
  matplotlib:
    Type: String
    Default: matplotlib.zip
  s3bucketnamereports:
    Type: String
    Default: ato-dis-infra-build-pipeline-outputs-devtest
  lambdazip:
    Type: String
    Default: approval.zip
  subnetlist:
    Type: String
    Default: "['subnet-0fb54d79' , 'subnet-0c03b384cc7d98682']"
  vpc6bcfd80e:
    Type: String
  sg0932df5016b614b95:
    Type: String
Resources:
  atodisgeneratereport67672E44:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: s3bucketname
        S3Key:
          Ref: lambdazip
      Environment:
        Variables:
          s3_bucket:
            Ref: s3bucketname
          s3_bucket_reports:
            Ref: s3bucketnamereports
          config: config.json
          ARTIFACTORY_SVC_USER: udfh8
          ARTIFACTORY_SVC_USER_TOKEN: cmVmdGtuOjAxOjE3NTAxMjY4NDY6S2M2RUZzTkx5TndsZUN1azR1cms0TlpIeU0x
          ARTIFACTORY_ENDPOINT: https://artifactory.ctz.atocnet.gov.au
          ARTIFACTORY_REPO_STORAGE_PATH: /artifactory/disolution-generic-release-local/AWS/Reports/
      Handler: report_handler.handler
      MemorySize: 10240
      Role:
        Ref: lambdarole
      Runtime: python3.11
      Timeout: 600
    Metadata:
      aws:cdk:path: AutomatedTcmStack/ato-dis-generate_report/Resource
  disautomatedtcmmygovid65352089:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        EncryptionKey:
          Id:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":kms:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":"
                - Ref: kmsalias
          Type: KMS
        Location:
          Ref: s3bucketname
        Type: S3
      Name: dis-mygov-automated-tcm
      PipelineType: V2
      RestartExecutionOnUpdate: false
      RoleArn:
        Ref: admincbrole
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                S3Bucket:
                  Ref: s3bucketname
                S3ObjectKey:
                  Ref: vsslnzip
                PollForSourceChanges: true
              Name: S3Source
              OutputArtifacts:
                - Name: buildspec_artifact
              RoleArn:
                Ref: admincbrole
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: DISautomatedTCM47EA922F
                BatchEnabled: "true"
                CombineArtifacts: "true"
              InputArtifacts:
                - Name: buildspec_artifact
              Name: CodeBuild
              OutputArtifacts:
                - Name: automated-tcm
              RoleArn:
                Fn::GetAtt:
                  - disautomatedtcmmygovidbuildtestCodeBuildCodePipelineActionRole6FAB9B0D
                  - Arn
              RunOrder: 1
          Name: build_test
        - Actions:
            - ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: "1"
              Configuration:
                FunctionName:
                  Ref: atodisgeneratereport67672E44
              Name: GenerateReport
              RoleArn:
                Ref: admincbrole
              RunOrder: 1
          Name: build_report
    Metadata:
      aws:cdk:path: AutomatedTcmStack/dis-automated_tcm-mygovid/Resource
  disautomatedtcmmygovidbuildtestCodeBuildCodePipelineActionRole6FAB9B0D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: AutomatedTcmStack/dis-automated_tcm-mygovid/build_test/CodeBuild/CodePipelineActionRole/Resource
  disautomatedtcmmygovidbuildtestCodeBuildCodePipelineActionRoleDefaultPolicy1DC736D7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
              - codebuild:StopBuildBatch
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DISautomatedTCM47EA922F
                - Arn
        Version: "2012-10-17"
      PolicyName: disautomatedtcmmygovidbuildtestCodeBuildCodePipelineActionRoleDefaultPolicy1DC736D7
      Roles:
        - Ref: disautomatedtcmmygovidbuildtestCodeBuildCodePipelineActionRole6FAB9B0D
    Metadata:
      aws:cdk:path: AutomatedTcmStack/dis-automated_tcm-mygovid/build_test/CodeBuild/CodePipelineActionRole/DefaultPolicy/Resource
  DISautomatedTCM47EA922F:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      BuildBatchConfig:
        ServiceRole:
          Fn::GetAtt:
            - DISautomatedTCMBatchServiceRoleD073B7CC
            - Arn
      Cache:
        Type: NO_CACHE
      EncryptionKey:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":kms:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: kmsalias
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name: dis-automated-tcm
      ServiceRole:
        Ref: admincbrole
      Source:
        BuildSpec: s3://aha-health-aware-ato-john/buildspec.yml
        Type: CODEPIPELINE
    Metadata:
      aws:cdk:path: AutomatedTcmStack/DIS-automated-TCM/Resource
  DISautomatedTCMBatchServiceRoleD073B7CC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: AutomatedTcmStack/DIS-automated-TCM/BatchServiceRole/Resource
  DISautomatedTCMBatchServiceRoleDefaultPolicyB006E53B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:RetryBuild
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DISautomatedTCM47EA922F
                - Arn
        Version: "2012-10-17"
      PolicyName: DISautomatedTCMBatchServiceRoleDefaultPolicyB006E53B
      Roles:
        - Ref: DISautomatedTCMBatchServiceRoleD073B7CC
    Metadata:
      aws:cdk:path: AutomatedTcmStack/DIS-automated-TCM/BatchServiceRole/DefaultPolicy/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OywrCMBBFv8V9OmqluLfgOtQPkDQZcdo0KXkgEvrvalLR1T3M3DlMDfumgd1GPHwl1Vhp6iFdgpAja2+GCycmDOjYe39N/gCnKEcMJ+GRaTH1SkA6RyMDWfM5+PLCpFU404yaDELiK2XpygsjMUHqrM7jnNxqks/cylQ8fSStfhLu7IAy5FbBZWEdehudLKo/bq1RVF7iz3C3ZnuAfQ3HzeCJKhdNoAmhK/kCaixrug4BAAA=
    Metadata:
      aws:cdk:path: AutomatedTcmStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2

