version: 0.2
env:
  variables:
    S3_BUCKET: my-reports-bucket
    TOPIC_ARN: arn:aws:sns:us-east-1:123456789012:mySNSTopic
    GIT_REPO: example.com/git/pull
    SLN: test-api/test-api.csproj
    GIT_TEST: example commands to run | with piping
    DOTNETVER: latest
phases:
  install:
    runtime-versions:
      dotnet: ${DOTNETVER}
  pre_build:
    commands:
      - echo Restore started on `date`
      - git clone ${GIT_REPO}
      - dotnet restore ${SLN}
  build:
    commands:
      - echo Build started on `date`
      - dotnet build ${SLN}
      - echo "Running dotnet cli and running tests"
      - ${GIT_TEST}
  post_build:
    commands:
      #- echo "Compressing the package.."
      #- cd ../outputDirectory
      #- zip -r myBuild.zip .
      #- echo "Uploading to S3.."
      #- aws s3 cp myBuild.zip s3://${S3_BUCKET}/myBuild.zip
      - echo "Done."
artifacts:
  files:
    - ./**/*
  reports:
    DotnetTestExamples:
      file-format: VisualStudioTrx
      files:
        - '**/*'
      base-directory: './testresults'