version: 0.2
env:
  variables:
    GIT_PASS: "1qcoToddHW1yYS8DkMb0QAJsPWTbwiy5OzFsKKFeOOgqlpItqJwrJQQJ99AKACAAAAAR4liXAAASAZDOnws0"
    REPO: "DIS.Solutions.AzureDevOpsPipelines"
    TEST_CMD: ""
phases:
    install:
        runtime-versions:
            dotnet: 8.0
    build:
      commands:
        - apt-get update -y && apt-get install -y git
        - echo "installing git"
        - git clone https://$GIT_PASS@dev.azure.com/atoado/EST/_git/$REPO
        - echo "cloning $REPO"
        - echo $TEST_CMD
